name: Sphinx Documentation

on:
  push:
    branches:
      - main  # 或你的主分支名称

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install sphinx furo myst_parser
          sudo apt-get install make

      - name: Build documentation
        run: |
          cd docs
          make clean
          make html
            
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          force_orphan: true